name: "Python CI"

on: push

jobs:
  test-backend:
    name: "âœ”ï¸ Test backend API"
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version:
        - '3.5'
        - '3.6'
    steps:
    - name: "ğŸ“¥ Check-out"
      uses: actions/checkout@v2
    - name: "ğŸ§° Install Python"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: "ğŸ§° Install Python requirements"
      run: pip install -r requirements.txt --quiet
    - name: "ğŸ“¥ Download NLTK tools"
      run: |
        python -m nltk.downloader stopwords
        python -m nltk.downloader punkt
        python -m nltk.downloader averaged_perceptron_tagger
    - name: "âœ”ï¸ Test API"
      run: python ./src/Backend/test.py
